### ISSUE TITLE
Unable to submit PR

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii-base-api#3]
I have completed the first step and will continue to improve.
Is it possible to merge my repo for my follow-up work. 
Related extensions I have temporarily submitted PR. Thanks
https://github.com/kids-return/yii-base-api
![image](https://user-images.githubusercontent.com/4520936/48660363-56175400-ea9b-11e8-9689-349ff7b104b3.png)

**Comment by kids-return** [comment]
@samdark @cebe @hiqsol

**Comment by samdark** [comment]
Your repository doesn't seem to be a fork so no, can't submit pull request from it.

**Comment by rob006** [comment]
@samdark You can pull changes directly from his repo. There no way to fork empty repository, so you can't open regular PR against it.

**Comment by kids-return** [comment]
![image](https://user-images.githubusercontent.com/4520936/48670817-802f4b80-eb59-11e8-97a0-7b8108ae4dcb.png)

Can be initialized and submitted to packagist.org
Then I can submit the PR again.

**Comment by kids-return** [comment]
You also need to create `yii-base-cli` and submitted to packagist.org
https://github.com/yiisoft/yii-base-web/issues/45#issuecomment-415479940

**Comment by samdark** [comment]
I've init-ed repo. Sorry for not init-ing it earlier.
