### ISSUE TITLE
cannot download yiisoft/inflector 

### ISSUE THREAD

**Issue by prawee** [yiisoft/yii-base-api#8]
Package operations: 46 installs, 0 updates, 0 removals
  - Installing hiqdev/composer-config-plugin (dev-master 4f8d841): Cloning 4f8d841d57 from cache
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing psr/log (1.1.0): Loading from cache
  - Installing psr/simple-cache (1.0.1): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.11.0): Loading from cache
  - Installing vlucas/phpdotenv (v2.6.1): Loading from cache
  - Installing yiisoft/strings (dev-master b0de650): Cloning b0de6507c2 from cache
  - Installing yiisoft/inflector (dev-master 5fe21d8): Cloning 5fe21d8c00
    Failed to download yiisoft/inflector from source: Failed to clone https://github.com/yiisoft/inflector.git via https, ssh protocols, aborting.

- https://github.com/yiisoft/inflector.git
  Cloning into '/private/var/www/yii3-rest/vendor/yiisoft/inflector'...
  remote: Repository not found.
  fatal: repository 'https://github.com/yiisoft/inflector.git/' not found

- git@github.com:yiisoft/inflector.git
  Cloning into '/private/var/www/yii3-rest/vendor/yiisoft/inflector'...
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

    Now trying to download from dist

**Comment by samdark** [comment]
It's part of https://github.com/yiisoft/strings.
